### ISSUE TITLE
[Feature Request] - Recruitment Page

### ISSUE THREAD

**Issue by mhgorguk** [Mersey-Hub-Group/www.merseyhubgroup.org.uk#3]
**Is your feature request related to a problem? Please describe.**
A page for the public to see what volunteer positions there is and how to apply.

**Describe the solution you'd like**
A page with volunteer positions and a link to apply.

**Describe alternatives you've considered**
N/A

**Additional context**
Disscussion #4

**Comment by bambieuk** [comment]
### Tasks

- [ ] Create page URL.
- [ ] Integrate recruitment system into page.

**Comment by mhgorguk** [comment]
Completed.
